/**
 * Application Constants
 */

export const USER_ROLES = {
  STUDENT: 'STUDENT',
  MENTOR: 'MENTOR',
};

export const ENROLLMENT_STATUS = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ABANDONED: 'ABANDONED',
};

export const PROGRESS_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
};

export const ACTIVITY_TYPES = {
  LESSON_STARTED: 'LESSON_STARTED',
  LESSON_COMPLETED: 'LESSON_COMPLETED',
  COURSE_STARTED: 'COURSE_STARTED',
  COURSE_COMPLETED: 'COURSE_COMPLETED',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

export const PAGINATION_DEFAULTS = {
  PAGE: 1,
  LIMIT: 10,
  MAX_LIMIT: 100,
};

export const RECOMMENDATION_REASONS = {
  INCOMPLETE_LESSON: 'incomplete_lesson',
  LEAST_COMPLETED_COURSE: 'least_completed_course',
  MOST_RECENT_COURSE: 'most_recent_course',
  HIGHEST_PRIORITY: 'highest_priority',
};
